name: CI/CD Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ develop-branch ]

jobs:
  # 배포 Job
  deploy-label-ai2:
    name: Deploy to label-ai2
    runs-on: [ self-hosted, label-ai2 ] # AWS ./configure에서 사용할 label명
    steps:
      # GitHub Container Registry (GHCR) 로그인을 Docker Hub 로그인을 대체
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Hub에서 이미지 가져와 실행
      - name: Pull and run Docker image
        run: |
          docker pull devyoonji/webserver_repo:aiapi
          docker stop ai || true
          docker rm ai || true
          docker run -d -p 8000:8000 --name ai --restart always devyoonji/webserver_repo:aiapi
